<a href="https://colab.research.google.com/github/aRod209/pytorch-for-deep-learning/blob/main/lectures/00_pytorch_fundamentals.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## 00. PyTorch Fundamentals

Resource notebook: https://www.learnpytorch.io/00_pytorch_fundamentals/

If you have a question: https://github.com/mrdbourke/pytorch-deep-learning/discussions

In [ ]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.5.1+cu121


## Introduction To Tensors

## A great YouTube video answering the question: "What's a Tensor?"

In [ ]:
%%HTML
<iframe
  width="560"
  height="315"
  src="https://www.youtube.com/embed/f5liqUk0ZTw"
  title="YouTube video player"
  frameborder="0"
  allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share"
  allowfullscreen>
</iframe>

## Creating Tensors


PyTorch tensors are created using `torch.tensor()` = https://pytorch.org/docs/stable/tensors.html

In [ ]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [ ]:
# Dimension of scalar
scalar.ndim

0

In [ ]:
# Get the number back as a Python int
scalar.item()

7

In [ ]:
scalar.shape

torch.Size([])

In [ ]:
# Vector
vector = torch.tensor([7, 7])
vector

tensor([7, 7])

In [ ]:
# Dimension of vector
vector.ndim

1

In [ ]:
# Shape should be 2 for 2X1
vector.shape

torch.Size([2])

In [ ]:
# Matrix
MATRIX = torch.tensor([[7, 8],
                       [9, 10]])

MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [ ]:
MATRIX.ndim

2

In [ ]:
MATRIX[0], MATRIX[1]

(tensor([7, 8]), tensor([ 9, 10]))

In [ ]:
MATRIX.shape

torch.Size([2, 2])

In [ ]:
# TENSOR
TENSOR = torch.tensor([[[1,2,3],
                        [3,6,9],
                        [2,5,4]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 5, 4]]])

In [ ]:
TENSOR.ndim

3

In [ ]:
# There is 1 3X3 tensor
TENSOR.shape

torch.Size([1, 3, 3])

In [ ]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 5, 4]])

In [ ]:
# Experiment with tensors
TENSOR2 = torch.tensor([[[1,2],
                         [3,4]],
                        [[5,6],
                         [7,8]],])

In [ ]:
TENSOR2.shape

torch.Size([2, 2, 2])

In [ ]:
a = [i for i in range(10)]
b = [i for i in range(10,20)]
TENSOR3 = torch.tensor([[a,b]])

In [ ]:
TENSOR3

tensor([[[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
         [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]]])

In [ ]:
TENSOR3.shape

torch.Size([1, 2, 10])

### Random tensors

Why random tensors?

Random tensors are important because of the way many neural netwoks learn is that they start with tensors full of random numbers and then adjust those random numbers to better represent the data.

`Start with random numbers - look at data -> update random numbers -> look at data -> update random numbers`

torch random tensors: https://pytorch.org/docs/stable/generated/torch.randn.html

In [ ]:
# Create a random tensor of size (3,4)

random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.9766, 0.2935, 0.7109, 0.8604],
        [0.5661, 0.0466, 0.3748, 0.5202],
        [0.9560, 0.7985, 0.2337, 0.3914]])

In [ ]:
random_tensor.ndim

2

In [ ]:
random_tensor.shape

torch.Size([3, 4])

In [ ]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3,224, 224)) # height, width, coolour channel
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

In [ ]:
torch.rand(2, 9, 10)

tensor([[[0.1657, 0.5099, 0.8962, 0.9854, 0.7188, 0.9799, 0.0801, 0.6709,
          0.5066, 0.2483],
         [0.7387, 0.2624, 0.7648, 0.9003, 0.3853, 0.7075, 0.4409, 0.8162,
          0.9066, 0.7110],
         [0.8090, 0.2967, 0.4977, 0.5460, 0.8717, 0.4892, 0.4305, 0.4976,
          0.3935, 0.7627],
         [0.4524, 0.8672, 0.8150, 0.6147, 0.9223, 0.6871, 0.1395, 0.3377,
          0.2476, 0.9557],
         [0.8111, 0.7439, 0.9303, 0.3228, 0.5503, 0.2195, 0.9608, 0.9584,
          0.5298, 0.5393],
         [0.2128, 0.6978, 0.9119, 0.4006, 0.3368, 0.5772, 0.0118, 0.6925,
          0.1321, 0.5953],
         [0.8707, 0.6756, 0.3105, 0.9394, 0.0035, 0.1061, 0.2820, 0.1101,
          0.6370, 0.1600],
         [0.8319, 0.6402, 0.1088, 0.4835, 0.9850, 0.0102, 0.5846, 0.1547,
          0.3753, 0.7180],
         [0.9256, 0.3726, 0.3178, 0.5986, 0.7406, 0.4963, 0.6989, 0.0771,
          0.3851, 0.9403]],

        [[0.7311, 0.6450, 0.7669, 0.5994, 0.5848, 0.5733, 0.5764, 0.3615,
          0.518

In [ ]:
torch.rand(size=(3,3,3))

tensor([[[0.4195, 0.9585, 0.4318],
         [0.6216, 0.3635, 0.5881],
         [0.9434, 0.5135, 0.5762]],

        [[0.5207, 0.7780, 0.8499],
         [0.8351, 0.4471, 0.6188],
         [0.4717, 0.9736, 0.0573]],

        [[0.8590, 0.8540, 0.1028],
         [0.2813, 0.2978, 0.4624],
         [0.1521, 0.1038, 0.6522]]])

### Zeros and ones

In [ ]:
# Create a tensor of all zzeros
zeros = torch.zeros(size=(3, 4))
zeros

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
zeros * random_tensor

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
# Create tensor of all ones
ones = torch.ones(size=(3, 4))
ones

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])

In [ ]:
ones.dtype

torch.float32

In [ ]:
random_tensor.dtype

torch.float32

### Creating a range of tensors and tensors-like

In [ ]:
# Use torch.range() and get deprecated message, use torch.arange()
one_to_ten = torch.arange(start=0, end=11, step=1)
one_to_ten

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [ ]:
torch.__version__

'2.5.1+cu121'

In [ ]:
# Creating tensors like
ten_zeros = torch.zeros_like(one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

### Tensor datatypes

**Note:** Tensor datatypes is one of the 3 big errors with PyTorch & deep learning:
1. Tensors not right datatype
2. Tensors not right shape
3. Tensors not on the right device

Precision in computing: https://en.wikipedia.org/wiki/Precision_(computer_science)

In [ ]:
# Float 32 tensor
float_32_tensor = torch.tensor([3.0, 6.0, 9.0],
                               dtype=None, # what datatype is the tensor (e.g. float32 or float16)
                               device='cpu', # What device is your tensor on
                               requires_grad=False) # whether or not to track gradients with this tensor's operations

float_32_tensor

tensor([3., 6., 9.])

In [ ]:
float_32_tensor.dtype

torch.float32

In [ ]:
float_16_tensor = float_32_tensor.type(torch.half)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [ ]:
int_32_tensor = torch.tensor([3, 6, 9], dtype=torch.long)
int_32_tensor

tensor([3, 6, 9])

In [ ]:
float_32_tensor * int_32_tensor

tensor([ 9., 36., 81.])

### Getting information from tensors (tensor attributes)

1. Tensors not right datatype - to do get datatype from a tensor, can use `tensor.dtype`
2. Tensors not right shape - to get shape from tensor, can use `tensor.shape`
3. Tensors not on the right device - to get device from a tensor, can use `tensor.device`

In [ ]:
# Create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.7711, 0.1181, 0.2090, 0.9085],
        [0.0596, 0.7024, 0.2750, 0.3626],
        [0.5437, 0.1478, 0.1265, 0.2614]])

In [ ]:
# Find out details about some tensor ()
print(some_tensor)
print(f'Datatype of tensor: {some_tensor.dtype}')
print(f'Shape of tensor: {some_tensor.shape}') # or some_tensor.size() - a method
print(f'Device tensor is on: {some_tensor.device}')

tensor([[0.7711, 0.1181, 0.2090, 0.9085],
        [0.0596, 0.7024, 0.2750, 0.3626],
        [0.5437, 0.1478, 0.1265, 0.2614]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


### Manipulating Tensors (tensor operations)

Tensor operations include:
* Addition
* Subtraction
* Multiplication (element-wise)
* Division
* Matrix multiplication

In [ ]:
# Create a tensor and add 10 to it
tensor = torch.tensor([1, 2, 3])
tensor + 10

tensor([11, 12, 13])

In [ ]:
# Subtract 10
tensor - 10

tensor([-9, -8, -7])

In [ ]:
# Multiply tensor by 10
tensor * 10

tensor([10, 20, 30])

In [ ]:
# Try out PyTorch in-built functions
torch.mul(tensor, 10)

tensor([10, 20, 30])

In [ ]:
torch.add(tensor, 10)

tensor([11, 12, 13])

In [ ]:
tensor * 2 / 2

tensor([1., 2., 3.])

### Matrix multiplication

Two main ways of performing mulitplication in neural networks and deep learning:

1. Element-wise multiplication
2. Matrix mulitplication

There are two main rules that performing matrix multiplication needs to satisfy:

1. The **inner dimensions** must match:
* (3, 2) @ (3,2) won't work
* (2, 3) @ (3, 2) will work
* (3, 2) @ (2, 3) will work
2. The resulting matrix has the shape of the **outer dimensions**:
* (2, 3) @ (3, 2) -> (2, 2)
* (3, 2) @ (2, 3) - > (3, 3)

In [ ]:
torch.rand(3, 2) @ torch.rand(3 ,2)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [ ]:
torch.rand(2, 3) @ torch.rand(3, 2)

tensor([[0.3818, 0.6266],
        [0.8844, 1.0586]])

In [ ]:
torch.rand(3, 2) @ torch.rand(2, 3)

tensor([[0.3372, 0.2171, 0.2118],
        [0.5311, 0.3351, 0.3420],
        [0.2773, 0.1521, 0.2062]])

In [ ]:
# Element wise multiplication
print(tensor, '*', tensor)
print(f'Equals {tensor * tensor}')

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals tensor([1, 4, 9])


In [ ]:
# Matrix multiplication
torch.matmul(tensor, tensor)

tensor(14)

In [ ]:
tensor

tensor([1, 2, 3])

In [ ]:
# Matrix multiplication by hand
1*1 + 2*2 + 3*3

14

In [ ]:
%%time
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]

value

CPU times: user 1.39 ms, sys: 50 µs, total: 1.44 ms
Wall time: 1.51 ms


tensor(14)

In [ ]:
%%time
torch.matmul(tensor, tensor)

CPU times: user 394 µs, sys: 51 µs, total: 445 µs
Wall time: 369 µs


tensor(14)

### One of the most common errors in deep learning: shape errors

In [ ]:
# Shapes for matrix multiplication
tensor_A = torch.tensor([[1, 2],
                         [3, 4],
                         [5, 6]])

tensor_B = torch.tensor([[7 ,10],
                         [8, 11],
                         [9, 12]])

torch.matmul(tensor_A, tensor_B) # torch.mm is the same as torch.matmul (it's an alias for matrix multiplication)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

In [ ]:
tensor_A.shape, tensor_B.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

To fix our tensor shape issues, we can manipulate the shape of one of our tensors using a **transpose.**

A **transpose** switches the axes or dimensions of a given tensor.

In [ ]:
tensor_B, tensor_B.shape

(tensor([[ 7, 10],
         [ 8, 11],
         [ 9, 12]]),
 torch.Size([3, 2]))

In [ ]:
tensor_B.T, tensor_B.T.shape

(tensor([[ 7,  8,  9],
         [10, 11, 12]]),
 torch.Size([2, 3]))

In [ ]:
# the matrix multiplication operation works when tensor_B is transposed
print(f'Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}')
print(f'New shapes: tensor_A = {tensor_A.shape} (same shape as above) tensor_B.T = {tensor_B.T.shape}')
print(f'Mulitplying: {tensor_A.shape} @ {tensor_B.T.shape} <- inner dimensions must match.')
print('Output:\n')
output = torch.matmul(tensor_A, tensor_B.T)
print(output)
print(f'\nOutput shape: {output.shape}')

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])
New shapes: tensor_A = torch.Size([3, 2]) (same shape as above) tensor_B.T = torch.Size([2, 3])
Mulitplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match.
Output:

tensor([[ 27,  30,  33],
        [ 61,  68,  75],
        [ 95, 106, 117]])

Output shape: torch.Size([3, 3])


## Finding the min, max, mean, sum etc (tensor aggregation)

In [ ]:
# Create a tensor
x = torch.arange(0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
# Find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [ ]:
# Find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [ ]:
x.dtype

torch.int64

In [ ]:
# Find the mean - note: the torch.mean() function requires a tensor of float 32 datatype to work.
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()

(tensor(45.), tensor(45.))

In [ ]:
# Find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

## Finding the positional min and max

In [ ]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
# Find the position in the tensor that has the minimum value with argmin() -> returns index position of target tensor where the minimum value occurs.
x = np.arange(1, 100, 10)
x.argmin()

0

In [ ]:
x[0]

1

In [ ]:
# Find the position in the tensor that has the maximum value with argmax()
x.argmax()

9

In [ ]:
x[9]

91

## Reshaping , stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the orignal tensor
* Stacking - combine multiple tensors on top of eachother (vstack) or side-by-side (hstack)
* Squeeze - removes all `1` dimensions from a tensor
* Unqueeze - add a `1` dimension to a target tensor
* Permute - Return a view of the input with dimension permuted (swapped) in a certain way

In [ ]:
# Let's create a tensor
import torch
x = torch.arange(1., 10.)
x, x.shape, x.ndim

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]), 1)

In [ ]:
# Add an extra dimension - has to be compatible with the original size
x_reshaped = x.reshape(1, 9)
x_reshaped, x_reshaped.shape, x_reshaped.ndim,  x_reshaped.dtype

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 torch.Size([1, 9]),
 2,
 torch.float32)

In [ ]:
# Chage the view
z = x.view(1, 9)
z, z.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [ ]:
x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [ ]:
# Chaging z changes x (because a view of a tensor shares the same memory as the original tensor)
z[:, 0] = 5
z, x

(tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]]),
 tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.]))

In [ ]:
# Stack tensors on top of each other.
x_stacked = torch.stack([x, x, x, x], dim=0)
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
x_stacked = torch.stack([x, x, x, x], dim=1)
x_stacked

tensor([[5., 5., 5., 5.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [4., 4., 4., 4.],
        [5., 5., 5., 5.],
        [6., 6., 6., 6.],
        [7., 7., 7., 7.],
        [8., 8., 8., 8.],
        [9., 9., 9., 9.]])

In [ ]:
x_stacked = torch.vstack([x, x, x, x])
x_stacked

tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.],
        [5., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [ ]:
x_stacked = torch.hstack([x, x, x, x])
x_stacked

tensor([5., 2., 3., 4., 5., 6., 7., 8., 9., 5., 2., 3., 4., 5., 6., 7., 8., 9.,
        5., 2., 3., 4., 5., 6., 7., 8., 9., 5., 2., 3., 4., 5., 6., 7., 8., 9.])

In [ ]:
# torch.squeeze() - removes all single dimensions from a target tensor
print(f'Previous tensor: {x_reshaped}')
print(f'Previous shape: {x_reshaped.shape}')

# Remove extra dimensions form x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f'\nNew tensor: {x_squeezed}')
print(f'New shpae; {x_squeezed.shape}')

Previous tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous shape: torch.Size([1, 9])

New tensor: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
New shpae; torch.Size([9])


In [ ]:
# torch.unsqueeze() - adds a single dimension to a target tensor at a specific dim (dimension)
print(f'Previous target: {x_squeezed}')
print(f'Previos shape: {x_squeezed.shape}')

# Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f'\nNew tensor: {x_unsqueezed}')
print(f'New shape: {x_unsqueezed.shape}')

Previous target: tensor([5., 2., 3., 4., 5., 6., 7., 8., 9.])
Previos shape: torch.Size([9])

New tensor: tensor([[5., 2., 3., 4., 5., 6., 7., 8., 9.]])
New shape: torch.Size([1, 9])


In [ ]:
# torch.permute - rearranges the dimensions of a target tensor in a specified order
x_original = torch.rand(size=(224, 224, 3)) # [height, width, colour_channels]
x_original, x_original.shape

(tensor([[[0.8672, 0.7755, 0.7119],
          [0.4787, 0.8433, 0.6098],
          [0.0206, 0.9849, 0.5864],
          ...,
          [0.3511, 0.1396, 0.4571],
          [0.6128, 0.0629, 0.2124],
          [0.2937, 0.0626, 0.1588]],
 
         [[0.5646, 0.5662, 0.3465],
          [0.3763, 0.3869, 0.4344],
          [0.2330, 0.5356, 0.0058],
          ...,
          [0.1071, 0.8668, 0.2389],
          [0.9146, 0.7538, 0.1760],
          [0.5724, 0.0694, 0.7118]],
 
         [[0.0464, 0.8367, 0.5703],
          [0.5478, 0.8388, 0.5417],
          [0.7981, 0.9880, 0.0496],
          ...,
          [0.5962, 0.8054, 0.8089],
          [0.6470, 0.7318, 0.2566],
          [0.5363, 0.4233, 0.4605]],
 
         ...,
 
         [[0.9669, 0.0704, 0.8237],
          [0.5141, 0.4284, 0.7215],
          [0.8886, 0.6030, 0.8082],
          ...,
          [0.4945, 0.2570, 0.6574],
          [0.1307, 0.8442, 0.2563],
          [0.9845, 0.4976, 0.9789]],
 
         [[0.7201, 0.9623, 0.6615],
          [0

In [ ]:
# Permute the orignal tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0
x_permuted, x_permuted.shape

(tensor([[[0.8672, 0.4787, 0.0206,  ..., 0.3511, 0.6128, 0.2937],
          [0.5646, 0.3763, 0.2330,  ..., 0.1071, 0.9146, 0.5724],
          [0.0464, 0.5478, 0.7981,  ..., 0.5962, 0.6470, 0.5363],
          ...,
          [0.9669, 0.5141, 0.8886,  ..., 0.4945, 0.1307, 0.9845],
          [0.7201, 0.8430, 0.9084,  ..., 0.6287, 0.2045, 0.5241],
          [0.1928, 0.2443, 0.6316,  ..., 0.8995, 0.2663, 0.2080]],
 
         [[0.7755, 0.8433, 0.9849,  ..., 0.1396, 0.0629, 0.0626],
          [0.5662, 0.3869, 0.5356,  ..., 0.8668, 0.7538, 0.0694],
          [0.8367, 0.8388, 0.9880,  ..., 0.8054, 0.7318, 0.4233],
          ...,
          [0.0704, 0.4284, 0.6030,  ..., 0.2570, 0.8442, 0.4976],
          [0.9623, 0.4825, 0.8806,  ..., 0.5087, 0.5602, 0.9395],
          [0.8873, 0.9511, 0.2089,  ..., 0.1983, 0.2859, 0.4638]],
 
         [[0.7119, 0.6098, 0.5864,  ..., 0.4571, 0.2124, 0.1588],
          [0.3465, 0.4344, 0.0058,  ..., 0.2389, 0.1760, 0.7118],
          [0.5703, 0.5417, 0.0496,  ...,

In [ ]:
x_original, x_original.shape

(tensor([[[0.8672, 0.7755, 0.7119],
          [0.4787, 0.8433, 0.6098],
          [0.0206, 0.9849, 0.5864],
          ...,
          [0.3511, 0.1396, 0.4571],
          [0.6128, 0.0629, 0.2124],
          [0.2937, 0.0626, 0.1588]],
 
         [[0.5646, 0.5662, 0.3465],
          [0.3763, 0.3869, 0.4344],
          [0.2330, 0.5356, 0.0058],
          ...,
          [0.1071, 0.8668, 0.2389],
          [0.9146, 0.7538, 0.1760],
          [0.5724, 0.0694, 0.7118]],
 
         [[0.0464, 0.8367, 0.5703],
          [0.5478, 0.8388, 0.5417],
          [0.7981, 0.9880, 0.0496],
          ...,
          [0.5962, 0.8054, 0.8089],
          [0.6470, 0.7318, 0.2566],
          [0.5363, 0.4233, 0.4605]],
 
         ...,
 
         [[0.9669, 0.0704, 0.8237],
          [0.5141, 0.4284, 0.7215],
          [0.8886, 0.6030, 0.8082],
          ...,
          [0.4945, 0.2570, 0.6574],
          [0.1307, 0.8442, 0.2563],
          [0.9845, 0.4976, 0.9789]],
 
         [[0.7201, 0.9623, 0.6615],
          [0

In [ ]:
print(f'Previous shape: {x_original.shape}') #[colour_chanel, height, width]
print(f'New shape: {x_permuted.shape}')

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


In [ ]:
x_original[0, 0, 0]

tensor(0.8672)

In [ ]:
x_permuted[0, 0, 0]

tensor(0.8672)

In [ ]:
x_permuted[0, 0, 0] = .999

In [ ]:
x_permuted[0, 0, 0]

tensor(0.9990)

In [ ]:
x_original[0, 0, 0]

tensor(0.9990)

## Indexing (selecting data from tensors)

Indexing with PyTorch is similar to indexing with NumPy.

In [ ]:
# Create a tensor
import torch
x = torch.arange(1, 10).reshape(1, 3, 3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [ ]:
# Let's index on our new tensor (dim=0)
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [ ]:
# Let's index on the middle bracket (dim=1)
x[0][0], x[0, 0]

(tensor([1, 2, 3]), tensor([1, 2, 3]))

In [ ]:
# Let's index on the most inner bracket (last dimension)
x[0][0][0], x[0,0,0]

(tensor(1), tensor(1))

In [ ]:
# You can also use ":" to select "all" of a target dimension
x[:, 0]

tensor([[1, 2, 3]])

In [ ]:
# Get all values of 0th and 1st dimensions but only index 1 of 2nd dimension
x[:, :, 1]

tensor([[2, 5, 8]])

In [ ]:
# Get all vaues of the 0 dimension but only the 1 index value of 1st and 2nd dimension
x[:, 1, 1]

tensor([5])

In [ ]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0, 0, :]

tensor([1, 2, 3])

In [ ]:
# Index on x to return 9
x[0,2,2]

tensor(9)

In [ ]:
# Index on x to return 3, 6 9
x[0, :, 2]

tensor([3, 6, 9])

## PyTorch tensors & NumPy

NumPy is a popular scientific Python numerical computing library.

And because of this, PyTorch has functionality to interact with it.

* Data in NumPy, want in PyTorch tensor -> `torch.from_numpy(ndarray)`
* PyTorch tensor -> NumPy -> `torch.Tensor.numpy()`

In [ ]:
# NumPy array to tensor
import torch
import numpy as np

array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array) # warning: when converting from numpy -> pytorch, pytorch relfects numpy's default datatype of float64 unless otherwise specifiec. See below.
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [ ]:
array.dtype

dtype('float64')

In [ ]:
tensor.dtype

torch.float64

In [ ]:
# But the default tensor data type is float 32
torch.arange(1.0, 8.0).dtype

torch.float32

In [ ]:
# Make sure of type, other than default, on initialization
tensor = torch.from_numpy(array).type(torch.float32)
tensor.dtype

torch.float32

In [ ]:
# Chage the value of array, what will this do to `tensor`?
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]), tensor([1., 2., 3., 4., 5., 6., 7.]))

In [ ]:
# Tensor to NumPy array
tensor = torch.ones(7)
numpy_tensor = tensor.numpy()
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [ ]:
# warning: when converting from pytorch -> numpy, numpy relfects pytorch's default datatype of float32 unless otherwise specifiec. See below.
tensor.dtype, numpy_tensor.dtype

(torch.float32, dtype('float32'))

In [ ]:
# Change the tensor, what happens to `numpy_tensor`?
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility (trying to take random out of random)

In short how a neural network learns:

`start with random numbers -> tensor operations -> update random numbers to try and make them better representations of the data -> again -> again -> again...`

To reduce the randomness in neural networks and PyTorch comes the concept of a **random seed**.

Essentially what the random seed does is "flavour" the randomness.

In [ ]:
import torch

# Create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)

tensor([[0.7707, 0.3881, 0.4534, 0.4578],
        [0.3554, 0.3222, 0.0742, 0.4190],
        [0.7450, 0.7292, 0.6043, 0.6903]])
tensor([[0.0980, 0.4919, 0.8097, 0.9370],
        [0.2755, 0.1023, 0.5940, 0.8923],
        [0.5141, 0.8238, 0.0253, 0.6170]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [ ]:
# Let's make some random but reproducible tensors
import torch

# Set the random seed
RANDOM_SEED = 369
torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(3, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(3, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.3998, 0.6201, 0.9229, 0.0735],
        [0.8979, 0.8878, 0.9014, 0.5796],
        [0.4578, 0.3855, 0.9865, 0.2216]])
tensor([[0.3998, 0.6201, 0.9229, 0.0735],
        [0.8979, 0.8878, 0.9014, 0.5796],
        [0.4578, 0.3855, 0.9865, 0.2216]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


Extra resources for reproducibility:
* https://pytorch.org/docs/stable/notes/randomness.html
* https://en.wikipedia.org/wiki/Random_seed

## Running tensors and PyTorch objects on the GPUs (and making faster computations)

GPUs = faster computation on numbers, thanks to CUDA + NVIDIA + PyTorch working behind the scenes to make everything hunky dory (good).

### 1. Getting a GPU

1. Easiest - Use Google Colab for a free GPU (options to upgrade as well)
2. Use your own GPU - takes a little bit of setup and requires the investment of purchasing a GPU, there's lots of options..., see online for what option to get.
3. Use cloud computing - GCP, AWS, Azure, these services allow you to rent computers on the cloud and access them.

For 2, 3 PyTorch + GPU drivers (CUDA) takes a little bit of setting up, to do this, refer to PyTorch setup documentation: https://pytorch.org/get-started/locally/


In [ ]:
!nvidia-smi

Sat Jan 18 15:44:14 2025       
+---------------------------------------------------------------------------------------+
| NVIDIA-SMI 535.104.05             Driver Version: 535.104.05   CUDA Version: 12.2     |
|-----------------------------------------+----------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |         Memory-Usage | GPU-Util  Compute M. |
|                                         |                      |               MIG M. |
|=========================================+======================+======================|
|   0  Tesla T4                       Off | 00000000:00:04.0 Off |                    0 |
| N/A   43C    P8              12W /  70W |      0MiB / 15360MiB |      0%      Default |
|                                         |                      |                  N/A |
+-----------------------------------------+----------------------+--

### 2. Check for GPU access with PyTorch

In [ ]:
# Check for GPU access with PyTorch
import torch
torch.cuda.is_available()

True

For PyTorch since it's capable of running compute on the GPU or CPU, it's best practice to setup device agnostic code: https://pytorch.org/get-started/locally/

E.g. run on GPU if availalbe, else default to CPU

In [ ]:
# Setup device agnostic code
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cuda'

In [ ]:
# Count number of devices
torch.cuda.device_count()

1

## 3. Putting tensors (and models) on the GPU

The reason we want our tensors/models on the GPU is because using a GPU results in faster computations.

In [ ]:
# Create a tensor (default on the CPU)
tensor = torch.tensor([1, 2, 3])

# Tensor no on GPU
print(tensor, tensor.device)

tensor([1, 2, 3]) cpu


In [ ]:
# Move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

### 4. Moving tensors back to the CPU

In [ ]:
# If tensor is on GPU, can't transorm it to NumPy
tensor_on_gpu.numpy()

TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first.

In [ ]:
# To fix the GPU tensor with NumPy issue, we can first set it to the CPU
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([1, 2, 3])

In [ ]:
# This should be unchanged
tensor_on_gpu

tensor([1, 2, 3], device='cuda:0')

## Exercises & Extra-cuurriculum

See exercises for this notebook here: https://www.learnpytorch.io/00_pytorch_fundamentals/#exercises