<a href="https://colab.research.google.com/github/aRod209/pytorch-for-deep-learning/blob/main/00_pytorch_exercises.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import torch
import numpy as np

1. Documentation reading - A big part of deep learning (and learning to code in general) is getting familiar with the documentation of a certain framework you're using. We'll be using the PyTorch documentation a lot throughout the rest of this course. So I'd recommend spending 10-minutes reading the following (it's okay if you don't get some things for now, the focus is not yet full understanding, it's awareness). See the documentation on [torch.Tensor](https://pytorch.org/docs/stable/tensors.html#torch-tensor) and for [torch.Cuda](https://pytorch.org/docs/master/notes/cuda.html#cuda-semantics).

In [ ]:
# 2. Create a random tensor with shape (7, 7).
x = torch.rand((7,7))
x

tensor([[0.2766, 0.2692, 0.8655, 0.1750, 0.6118, 0.9960, 0.0675],
        [0.6443, 0.9388, 0.1015, 0.4497, 0.8689, 0.6739, 0.8166],
        [0.8761, 0.2859, 0.3114, 0.0512, 0.8801, 0.6874, 0.4297],
        [0.0645, 0.9965, 0.2914, 0.8616, 0.1682, 0.6127, 0.2605],
        [0.8801, 0.0333, 0.2434, 0.1795, 0.6944, 0.2206, 0.3885],
        [0.1183, 0.6090, 0.7059, 0.8416, 0.6579, 0.6549, 0.1870],
        [0.8069, 0.7312, 0.6258, 0.1175, 0.4356, 0.5946, 0.2049]])

In [ ]:
# 3. Perform a matrix multiplication on the tensor from 2 with another random tensor with
# shape (1, 7) (hint: you may have to transpose the second tensor).
y = torch.rand((1,7))
print(f'x:\n{x}\n')
print(f'y:\n{y}\n')
print(f'y.T:\n{y.T}\n')
print(f'x * y.T: {np.dot(x, y.T)}\n')

x:
tensor([[0.2766, 0.2692, 0.8655, 0.1750, 0.6118, 0.9960, 0.0675],
        [0.6443, 0.9388, 0.1015, 0.4497, 0.8689, 0.6739, 0.8166],
        [0.8761, 0.2859, 0.3114, 0.0512, 0.8801, 0.6874, 0.4297],
        [0.0645, 0.9965, 0.2914, 0.8616, 0.1682, 0.6127, 0.2605],
        [0.8801, 0.0333, 0.2434, 0.1795, 0.6944, 0.2206, 0.3885],
        [0.1183, 0.6090, 0.7059, 0.8416, 0.6579, 0.6549, 0.1870],
        [0.8069, 0.7312, 0.6258, 0.1175, 0.4356, 0.5946, 0.2049]])

y:
tensor([[0.3651, 0.6209, 0.4471, 0.9882, 0.7171, 0.2298, 0.9152]])

y.T:
tensor([[0.3651],
        [0.6209],
        [0.4471],
        [0.9882],
        [0.7171],
        [0.2298],
        [0.9152]])

x * y.T: [[1.5574586]
 [2.833174 ]
 [1.8696151]
 [2.123819 ]
 [1.5324389]
 [2.3620834]
 [1.7810941]]



In [ ]:
# 4. Set the random seed to 0 and do exercises 2 & 3 over again.
RANDOM_SEED = 0
torch.manual_seed(RANDOM_SEED)
x = torch.rand(7,7)

torch.manual_seed(RANDOM_SEED)
y = torch.rand(1,7)

print(f'x:\n{x}\n')
print(f'y:\n{y}\n')
print(f'y.T:\n{y.T}\n')
print(f'np.dot(x, y.T):\n {np.dot(x, y.T)}\n')
print(f'torch.matmul(x, y.T):\n{torch.matmul(x, y.T)}')

x:
tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901],
        [0.8964, 0.4556, 0.6323, 0.3489, 0.4017, 0.0223, 0.1689],
        [0.2939, 0.5185, 0.6977, 0.8000, 0.1610, 0.2823, 0.6816],
        [0.9152, 0.3971, 0.8742, 0.4194, 0.5529, 0.9527, 0.0362],
        [0.1852, 0.3734, 0.3051, 0.9320, 0.1759, 0.2698, 0.1507],
        [0.0317, 0.2081, 0.9298, 0.7231, 0.7423, 0.5263, 0.2437],
        [0.5846, 0.0332, 0.1387, 0.2422, 0.8155, 0.7932, 0.2783]])

y:
tensor([[0.4963, 0.7682, 0.0885, 0.1320, 0.3074, 0.6341, 0.4901]])

y.T:
tensor([[0.4963],
        [0.7682],
        [0.0885],
        [0.1320],
        [0.3074],
        [0.6341],
        [0.4901]])

np.dot(x, y.T):
 [[1.5984519 ]
 [1.1173093 ]
 [1.2740741 ]
 [1.6837609 ]
 [0.82785815]
 [1.0347089 ]
 [1.2498218 ]]

torch.matmul(x, y.T):
tensor([[1.5985],
        [1.1173],
        [1.2741],
        [1.6838],
        [0.8279],
        [1.0347],
        [1.2498]])


In [ ]:
# 5. Speaking of random seeds, we saw how to set it with torch.manual_seed() but is there a GPU equivalent?
# (hint: you'll need to look into the documentation for torch.cuda for this one). If there is, set the GPU random seed to 1234.
torch.cuda.is_available()

True

In [ ]:
# Setup device agnositc code
device = 'cuda' if torch.cuda.is_available() else 'cpu'
device

'cuda'

In [ ]:
RANDOM_SEED = 1234

# 6. Create two random tensors of shape (2, 3) and send them both to the GPU (you'll need access to a GPU for this).
# Set torch.manual_seed(1234) when creating the tensors (this doesn't have to be the GPU random seed).
torch.cuda.manual_seed(RANDOM_SEED)
x = torch.rand(size=(2,3), device=device)

torch.cuda.manual_seed(RANDOM_SEED)
y = torch.rand(size=(2,3), device=device)

# 7. Perform a matrix multiplication on the tensors you created in 6 (again, you may have to adjust the shapes of one of the tensors).
z = torch.matmul(x, y.T)
print(f'x:\n{x}\n')
print(f'y:\n{y}\n')
print(f'y.T:\n{y.T}\n')
print(f'torch.matmul(x, y.T):\n {z}\n')

x:
tensor([[0.1272, 0.8167, 0.5440],
        [0.6601, 0.2721, 0.9737]], device='cuda:0')

y:
tensor([[0.1272, 0.8167, 0.5440],
        [0.6601, 0.2721, 0.9737]], device='cuda:0')

y.T:
tensor([[0.1272, 0.6601],
        [0.8167, 0.2721],
        [0.5440, 0.9737]], device='cuda:0')

torch.matmul(x, y.T):
 tensor([[0.9792, 0.8358],
        [0.8358, 1.4578]], device='cuda:0')



In [ ]:
# 8. Find the maximum and minimum values of the output of 7.
torch.max(z), torch.min(z)

(tensor(1.4578, device='cuda:0'), tensor(0.8358, device='cuda:0'))

In [ ]:
# 9. Find the maximum and minimum index values of the output of 7.
torch.argmax(z), torch.argmin(z)

(tensor(3, device='cuda:0'), tensor(1, device='cuda:0'))

In [ ]:
# 10. Make a random tensor with shape (1, 1, 1, 10) and then create a new tensor with all the 1 dimensions removed to be left with a tensor of shape (10).
# Set the seed to 7 when you create it and print out the first tensor and it's shape as well as the second tensor and it's shape.

RANDOM_SEED = 7

torch.manual_seed(RANDOM_SEED)
x = torch.rand((1,1,1,10))
y = x.flatten()
x, y

(tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
            0.3653, 0.8513]]]]),
 tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
         0.8513]))

In [ ]:
x.shape, y.shape

(torch.Size([1, 1, 1, 10]), torch.Size([10]))